/*
 * Copyright (c) 2020-2022 - for information on the respective copyright owner
 * see the NOTICE file and/or the repository at
 * https://github.com/hyperledger-labs/acapy-java-client
 *
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * aca-py client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.hyperledger.aries.api.present_proof_v2;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;
import java.util.Map;

/**
 * DIFPresSpec
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class DIFPresSpec {

    /**
     * Issuer identifier to sign the presentation, if different from current public DID
     */
    private String issuerId;

    private V2DIFProofRequest.PresentationDefinition presentationDefinition;

    /**
     * Mapping of input_descriptor id to list of stored W3C credential record_id
     * example: {@code "<input descriptor id_1>": ["<record id_1>", "<record id_2>"]}
     */
    private Map<String, List<String>> recordIds;

    /**
     * reveal doc [JSON-LD frame] dict used to derive the credential when selective disclosure is required
     */
    private Object revealDoc;
}
