/*
 * aca-py client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.hyperledger.aries.api.present_proof_v2;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hyperledger.aries.api.present_proof.PresentProofRequest;
import org.hyperledger.aries.config.GsonConfig;

import java.util.Optional;

/**
 * V20PresExRecordByFormat
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class V20PresExRecordByFormat {
    private JsonObject pres;
    private JsonObject presProposal;
    private JsonObject presRequest;

    public Optional<PresentProofRequest.ProofRequest> resolveIndyPresentationRequest() {
        if (presRequest != null) {
            JsonElement indy = presRequest.get("indy");
            if (indy != null) {
                return Optional.ofNullable(GsonConfig.defaultConfig().fromJson(indy, PresentProofRequest.ProofRequest.class));
            }
        }
        return Optional.empty();
    }
}
