/*
 * Copyright (c) 2020-2021 - for information on the respective copyright owner
 * see the NOTICE file and/or the repository at
 * https://github.com/hyperledger-labs/acapy-java-client
 *
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * aca-py client
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.hyperledger.aries.api.issue_credential_v2;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;

/**
 * V20CredExRecordByFormat
 */
@lombok.Data
@lombok.AllArgsConstructor
@lombok.NoArgsConstructor
@lombok.Builder
public class V20CredExRecordByFormat {
    private JsonObject credIssue;
    private JsonObject credOffer;
    private JsonObject credProposal;
    private JsonObject credRequest;

    public String getSchemaIdFromProposal() {
        String result = null;
        if (credProposal != null) {
            JsonElement indy = credProposal.get("indy");
            if (indy != null) {
                result = indy.getAsJsonObject().get("schema_id").getAsString();
            }
        }
        return result;
    }
}
